package edu.uiuc.cs427app;

import androidx.room.Database;
import androidx.room.Room;
import androidx.room.RoomDatabase;

import edu.uiuc.cs427app.dao.SelectedCityDao;
import edu.uiuc.cs427app.data.SelectedCity;

/**
 * AppDatabase: Represents the main database for the application.
 * This database uses the Room persistence library to provide an abstraction layer over SQLite.
 * Currently, the database contains one entity: SelectedCity.
 */
@Database(entities = {SelectedCity.class}, version = 1, exportSchema = false)
public abstract class AppDatabase extends RoomDatabase {

    /**
     * Provides an abstract method to access the SelectedCity data access object (DAO).
     * The actual implementation of this method is generated by the Room library during compilation.
     *
     * @return SelectedCityDao - the data access object for SelectedCity entity operations.
     */
    public abstract SelectedCityDao selectedCityDao();
}